create table
  public.users (
    id integer generated by default as identity,
    email character varying not null,
    password text not null,
    is_admin boolean not null default true,
    created_at timestamp with time zone not null default now(),
    constraint users_pkey primary key (id),
    constraint users_email_key unique (email),
    constraint users_password_key unique (password)
  ) tablespace pg_default;

create table
  public.bus (
    bus_id integer generated by default as identity,
    bus_number character varying not null,
    capacity integer not null,
    created_at timestamp with time zone not null default now(),
    constraint bus_pkey primary key (bus_id),
    constraint bus_bus_id_key unique (bus_id),
    constraint bus_bus_number_key unique (bus_number)
  ) tablespace pg_default;

create table
  public.ticket (
    ticket_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    bus_id integer not null,
    seat_number integer null,
    is_open boolean not null default false,
    user_details text null,
    constraint ticket_pkey primary key (ticket_id),
    constraint ticket_ticket_id_key unique (ticket_id),
    constraint ticket_bus_id_fkey foreign key (bus_id) references bus (bus_id)
  ) tablespace pg_default;